cloneone/cloneapp/urls.py
from django.urls import path
from cloneapp import views
from django.conf import settings
from django.conf.urls.static import static

app_name='cloneapp'


urlpatterns=[
        path('',views.firstpage,name='firstpage'),
        path('list/',views.frontpage.as_view(),name='question_list'),
        path('detail/<int:pk>/',views.detailpage.as_view(),name='question_detail'),
        path('update/<int:pk>/',views.updatepost.as_view(),name='question_update'),
        path('delete/<int:pk>/',views.deletequestion,name='delete_question'),
        path('questioncreate/',views.question_create,name='question_create'),
        path('usrinf/<int:pk>/',views.profile_user_info,name='userinfo'),
        path('draft/',views.draftquestions.as_view(),name='draft_question'),
        path('published/<int:pk>/',views.published_question,name='publish_question'),
        path('login/',views.login_user,name='login'),
        path('deleteanswer/<int:pk>/',views.delete_answer,name='delete_answer'),
        path('logout/',views.logout_user,name='logout'),
        path('registration/',views.register_user,name='registration'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cloneone/cloneone/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("cloneapp.urls"))
]

cloneone/cloneapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
# Create your models here.
class user_info(models.Model):
    user_p=models.ForeignKey(User,on_delete=models.CASCADE,related_name="userinf")
    studies=models.CharField(max_length=100,blank=True,null=True)
    home=models.CharField(max_length=300,blank=True,null=True)
    work=models.CharField(max_length=200,blank=True,null=True)
    image_field=models.ImageField(upload_to='profile_pic',blank=True)
class question(models.Model):
    author=models.ForeignKey(user_info,on_delete=models.CASCADE)
    question_title=models.CharField(max_length=100)
    published=models.BooleanField(default=False)
    publish_date=models.DateField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('cloneapp:question_detail',kwargs={'pk':self.pk})
    def publish(self):
        self.published=True
        self.publish_date=timezone.now()

class answerclass(models.Model):
    question_answer=models.ForeignKey(question,on_delete=models.CASCADE,related_name='question_ans')
    author_ans=models.ForeignKey(user_info,on_delete=models.CASCADE,related_name='user_information')
    title_ans=models.CharField(max_length=400)

cloneone/cloneapp/forms.py
from django import forms
from cloneapp.models import user_info,question,answerclass
from django.contrib.auth.models import User

class userprofile(forms.ModelForm):
    class Meta():
        model=User
        fields=['username','email','password']
        widgets={
        'password':forms.PasswordInput(),
        }

class registration_form(forms.ModelForm):
    class Meta():
        model=user_info
        fields=['studies','home','work','image_field']




class new_question_form(forms.ModelForm):
    class Meta():
        model=question
        fields=['question_title']

class answer_form(forms.ModelForm):
    class Meta():
        model=answerclass
        fields=['title_ans']

cloneone/cloneapp/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import ListView,DetailView,UpdateView,DeleteView,CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from cloneapp.forms import registration_form,new_question_form,userprofile,answer_form
from django.urls import reverse,reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth import login,logout,authenticate
from cloneapp.models import question,user_info,answerclass
from django.contrib.staticfiles.storage import staticfiles_storage

# Create your views here.
def firstpage(request):
    return render(request,'cloneapp/firstpage.html')
class frontpage(ListView):
    model=question
    template_name='question_list.html'
    queryset = question.objects.filter(published=True).order_by('-publish_date')

@login_required(login_url='/login/')
def question_create(request):
    if(request.method=='POST'):
        a=question()
        a.question_title=request.POST['question_tit']
        a.author = get_object_or_404(user_info,user_p=request.user)
        a.save()
        return HttpResponseRedirect(reverse('cloneapp:question_detail',kwargs={'pk':a.pk}))


def profile_user_info(request,pk):
    u=get_object_or_404(user_info,pk=pk)
    return render(request,'cloneapp/profile_user_inf.html',{'model':u})


class detailpage(DetailView):
    model=question
    template_name='question_detail.html'
    context_text_name='question'

    def post(self, request, * args, ** kwargs):
        answer_form=answerclass()
        answer_form.title_ans=request.POST['answerone']
        answer_form.author_ans=get_object_or_404(user_info,user_p=request.user)
        answer_form.question_answer=question.objects.get(pk=kwargs['pk'])
        answer_form.save()
        k=kwargs['pk']
        return HttpResponseRedirect(reverse('cloneapp:question_detail',kwargs={'pk':k}))

    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        answer_form=answerclass()
        context['comments']=answerclass.objects.filter(question_answer=context['question'])
        context['answer_form']=answer_form
        return context


class updatepost(LoginRequiredMixin,UpdateView):
    login_url='/login/'
    redirect_field_name='cloneapp/question_detail.html'
    form_class=new_question_form
    model=question
    context_text_name="form"


@login_required(login_url='/login/')
def deletequestion(request,pk):
    question_q=get_object_or_404(question,pk=pk)
    question_q.delete()
    return HttpResponseRedirect(reverse('cloneapp:question_list'))

class draftquestions(LoginRequiredMixin,ListView):
    login_url='/login/'
    model=question

    def get_queryset(self):
        return question.objects.filter(author__user_p = self.request.user).filter(published=False)


@login_required(login_url='/login/')
def published_question(request,pk):
    question_user=get_object_or_404(question,pk=pk)
    question_user.publish()
    question_user.save()
    return HttpResponseRedirect(reverse('cloneapp:question_detail',kwargs={'pk':pk}))

def login_user(request):
    if(request.method=='POST'):
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username,password=password)
        if(user):
            if(user.is_active):
                login(request,user)
    return HttpResponseRedirect(reverse('cloneapp:question_list'))


@login_required(login_url='/login/')
def delete_answer(request,pk):
    obj=get_object_or_404(answerclass,pk=pk)
    form_pk=obj.question_answer.pk
    obj.delete()
    return HttpResponseRedirect(reverse('cloneapp:question_detail',kwargs={'pk':form_pk}))


# @login_required(login_url='/login/')
# def edit_answer(request,pk):
#     obj=get_object_or_404(answerclass,pk)
#     if(request.method=='GET'):




@login_required(login_url='/login/')
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('cloneapp:question_list'))



def register_user(request):
    if(request.method=='POST'):
        form_user=registration_form(request.POST,request.FILES)
        form_profile=userprofile(data=request.POST)
        if(form_profile.is_valid() and form_user.is_valid()):
            form_profile=form_profile.save()
            form_profile.set_password(form_profile.password)
            form_profile.save()
            b=form_user.save(commit=False)
            b.user_p=form_profile
            if('image_field' in request.FILES):
                 b.image_field=request.FILES['image_field']
            else:
                url_image = staticfiles_storage.url('images/images.png')
                b.image_field=url_image
            b.save()
            return HttpResponseRedirect(reverse('cloneapp:question_list'))
        else:
            return render(request,'cloneapp/registration.html',{'form':form_user,'form_us':form_profile})

    else:
        form_info=userprofile()
        form_user=registration_form()
        return render(request,'cloneapp/registration.html',{'form':form_user,'form_us':form_info})

cloneone/cloneapp/templates/cloneapp/base.html
<!DOCTYPE html>
{% load static %}
{% load extra_tags %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Merienda" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Chela+One" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    {% block head %}
    {% endblock %}
  </head>
  <body>
    <nav class="nav navbar-expand-sm bg-dark navbar-dark fixed-top">
      <div class="navbar-brand">
      <a class="navbar-brand " href="{% url 'cloneapp:question_list' %}"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8UYVQPzyKYSQ_79-zmwNcmn9lPmN_JU8jb5Ie0Nn9qGU0y0xh" alt="Starhack" width:"30" height="30" ></a>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" date-target="#collapsecls"><span class="navbar-toggler-icon" ></span></button>
      <div class="collapse navbar-collapse" id="collapsecls">
        <ul class="navbar-nav navbar-left">
          <li class="nav-item"><a class="nav-link sign" href="{% url 'cloneapp:registration' %}"><i class="fas fa-users"></i>Sign up</a></li>
          {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link" href="{% url 'cloneapp:draft_question' %}"><i class="fas fa-clipboard-list"></i></a></li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item"><a class="nav-link" href="{% url 'cloneapp:logout' %}"><i class="fas fa-sign-out-alt"></i><img  src="{{ user|imageurl }}" alt="{{ user.use_info_set.image_field.url }}" class=" image-responsive rounded-circle" style="width:40px;"></a></li>
          {% endif %}
          </ul>
      </div>
    </nav>
    {% block a %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
  </body>
</html>

cloneone/cloneapp/templates/cloneapp/firstpage.html
{% extends 'cloneapp/base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'cloneapp/css.css' %}">
{% endblock %}
{% block a %}
<div class="container">
  <h2 class="display-1">Starhack</h2>
  <h3 class="centre">A Answer Book To All Of Your Question</h3>
</div>
{% endblock %}

cloneone/cloneapp/templates/cloneapp/profile_user_inf.html
{% extends 'cloneapp/base.html'%}
{% load staticfiles %}
{% block head %}
<link rel="stylesheet" href="{% static 'cloneapp/anothercss.css'%}">
{% endblock %}
{% block a %}
<div class="wq">
  <div class="card" style="width:400px; margin:100px auto;">
     <img class="card-img-top" src="{{ model.image_field.url }}" alt="userimage">
     <div class="card-body">
       <h3 class="card-title">{{ model.user_p.username}}</h3>
       {% if model.studies %}
       <p class="card-text">Studied at {{model.studies}}</p>
       {% endif %}
       {% if model.home %}
       <p class="card-text"> Lived at {{model.home}}</p>
       {% endif %}
       {% if model.work %}
       <p class="card-text "> Work at {{model.work}}</p>
       {% endif %}
     </div>
  </div>
</div>
{% endblock %}

cloneone/cloneapp/templates/cloneapp/question_detail.html
{% extends 'cloneapp/base.html'%}
{% load staticfiles %}
{% block head %}
<link rel="stylesheet" href="{% static 'cloneapp/anothercss.css' %}">
{% endblock %}
{% block a %}
<div class="jumbotron jumbotron-fluid">
  <h3 class="sign display-4">{{ question.question_title }}</h3>
  <div class="media border p-3">
    <a href="{% url 'cloneapp:userinfo' pk=question.author.pk %}"><img src="{{ question.author.image_field.url }}" alt="{{question.author.image_field.url }}"  class="mr-3 mt-3 rounded-circle" style="width:60px;"></a>
   <div class="media-body">
   <h4>{{ question.author.user.username }} <small><i>Posted on {{ question.publish_date|date:"D,d M, Y"}}</i></small></h4>
   {% if user.is_authenticated and user == question.author.user_p %}
   {% if not question.published %}
   <a href="{% url "cloneapp:publish_question" pk=question.pk %}"><i class="fas fa-check-double"></i></a>
   {% endif %}
   <a href="{% url "cloneapp:delete_question" pk=question.pk %}"><i class="fas fa-trash"></i></a>
   {% endif %}
  </div>
</div>
</div>
  {% for com in comments %}
  <div class="jumbotron">
   <div class="media border p-3">
     <div class="media-body">
       <h3>@{{ com.author_ans.user_p.username }}:</h3>
       <p>{{ com.title_ans }}</p>
       {% if user.is_authenticated and user == com.author_ans.user_p %}
       <a href="{% url "cloneapp:delete_answer" pk=com.pk %}"><i class="fas fa-trash"></i></a>
       {% endif %}
     </div>
      <a href="{% url 'cloneapp:userinfo' pk=com.author_ans.pk%}"><img src="{{ com.author_ans.image_field.url }}" alt="{{ com.author_ans.user_p.username }}" class="mr-3 mt-3 rounded-circle" style="width:60px;"></a>
   </div>
   </div>
  {% endfor %}

{% if user.is_authenticated %}
<form class="form-user"  method="POST">
  {% csrf_token %}
<div class="form-group">
  <input id="answero" type="text" name="answerone" placeholder="Your answer">
  </div>
<input id="submit_form"class="btn btn-outline-primary" type="submit" name="" value="Answer">
<br>
</form>
{% endif %}

{% endblock %}

cloneone/cloneapp/templates/cloneapp/question_list.html
{% extends 'cloneapp/base.html' %}
{% load staticfiles %}
{% block head %}
<link rel="stylesheet" href="{% static 'cloneapp/anothercss.css' %}">
{% endblock %}
{% block a %}
{% if not user.is_authenticated %}
<div class="jumbotron jumbotron-fluid jumbo">
  <div class="container">
    <h1>Starhack</h1>
    <p>Get knowlege from everywhere..</p>
    <form class="form-user" action="{% url 'cloneapp:login' %}" method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="username">Username:</label>
        <input type="text" name="username"class="form-control" placeholder="xyz123">
      </div>
      <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" name="password" class="form-control">
      </div>
      <input type="submit" class="btn btn-outline-primary" name="" value="Log in">
    </form>
  </div>

</div>
{% else %}
<div class="container">
  <div class="jumbotron">
    <form class="from-group" action="{% url 'cloneapp:question_create' %}" method="post">
      {% csrf_token %}
    <div class="form-group">
      <label for="question_ti">Question</label>
      <input type="text" name="question_tit" placeholder="Question Here">
    </div>
      <input class="btn btn-outline-primary" type="submit" name="" value="Post">
    </form>
  </div>

</div>
{% endif %}
{% for list in question_list %}
<div class="container">
<div class="jumbotron">
  <a href="{% url 'cloneapp:question_detail' pk=list.pk %}"><h3 class="sign text-dark"><strong>{{ list.question_title}}</strong></h3></a>
  <a href="{% url 'cloneapp:userinfo' pk=list.author.pk %}"><h4 class="text-right"><strong>@{{ list.author.user_p.username }}</strong><h4><img class="img-thumbnail float-right rounded-circle" src="{{ list.author.image_field.url }}" alt="@{{ list.author.user_p.username }}" width=100 height="100"></a>
  <a class="btn btn-primary"href="{% url 'cloneapp:question_detail' pk=list.pk %}">Answers<span class="badge badge-light">{{ list.question_ans.count }}</span></a>
</div>
</div>
{% endfor %}
</div>
{% endblock %}

cloneone/cloneapp/templates/cloneapp/registration.html
{% extends 'cloneapp/base.html' %}
{% load staticfiles %}
{% block head %}
<link rel="stylesheet" href="{% static 'cloneapp/anothercss.css' %}">
{% endblock %}
{% block a %}
<h1 class="cen">Create your account</h1>
<div class="container">
  <div class="jumbotron jumbo an">
    <form class="form-group" enctype="multipart/form-data" method="post">
      {{ form_us.errors }}
      {{ form.errors }}
      {% csrf_token %}
      <div class="form-group">
          {{ form_us.as_ul }}
      </div>
      <div class="form-group">
          {{ form.as_ul }}
      </div>
      <input id="button" type="submit" name="" value="Sign up">
    </form>
  </div>
</div>
{% endblock %}